// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxzhjbavefmgcymmllam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4emhqYmF2ZWZtZ2N5bW1sbGFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTU5ODIsImV4cCI6MjA2MTc3MTk4Mn0.hRFa3zlT9D_oqv2rFAvSD-I6xL__Tw5-YQypZFT5_rI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);